[package]
name = "cathode-ray-tube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
nom = "7.1.1"
itertools = "0.10.5"


[lib]
name = "io"
path = "../../lib/utilities/src/io.rs"